language: c++

compiler:
  - gcc

before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get install valgrind

# only invoke travis-ci for certain branches
branches:
  only:
    - master
    - dev

before_script:
  - skip

script:
  - skip

after_success:
  - skip

stages:
  - Unit Testing
  - Memory Check
  #- name: Upstream
  #  if: branch = master

jobs:
  include:
    - name: Unit Testing
      stage: Unit Testing
      before_script:
        - mkdir build_tests
        - cd build_tests || exit
        - cmake -DBUILD_TESTS=ON -DBUILD_DOCS=OFF -DWITH_OPENMP=ON ..
        - make
        - cd ..
      script:
        - cd build_tests || exit
        - ctest --verbose
        - cd ..
      after_success:
        - coveralls -e build_tests/googletest-src/ -e build_tests/googletest-build/ -e build_tests/CMakeFiles/ -e include/ -e tests/
    - name: Memory Check
      stage: Memory Check
      before_script:
        - mkdir build_tests
        - cd build_tests || exit
        - cmake -DBUILD_TESTS=ON -DBUILD_DOCS=OFF -DWITH_OPENMP=OFF ..
        - make
        - cd ..
      script:
        - cd build_tests || exit
        - ctest --overwrite MemoryCheckCommandOptions="--leak-check=full --error-exitcode=100" -T memcheck
        - cd ..
      after_success:
        - skip

notifications:
  email:
    recipients:
      - siavosh@ualberta.ca

    on_success: never # default: change
    on_failure: always # default: always
