language: c++

compiler:
  - gcc

before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get install valgrind

# only invoke travis-ci for certain branches
branches:
  only:
    - master
    - dev

before_script:
  - skip

script:
  - skip

after_success:
  - skip

stages:
  - Testing
  #- name: Upstream
  #  if: branch = master

jobs:
  include:
    - name: Testing
      stage: Testing
      before_script:
        - ./travis.sh build
      script:
        - ./travis.sh run
      after_success:
        - coveralls -e build_tests/googletest-src/ -e build_tests/googletest-build/ -e build_tests/CMakeFiles/ -e include/ -e tests/
    #- name:
    #    - Upstream
    #  stage:
    #    - Upstream
    #  install:
    #    - skip
    #  script: echo "hello" # TODO: replace this by a script which pushes to upstream branch (e.g. dev -> master)
    #  after_success:
    #    - skip

notifications:
  email:
    recipients:
      - siavosh@ualberta.ca

    on_success: never # default: change
    on_failure: always # default: always
